### ISSUE TITLE
用这种方法能否计算设置了行间距、段间距的文字呢？

### ISSUE THREAD

**Issue by QuintGao** [577528249/StringCalculate#1]
如题

**Comment by NotFound9** [comment]
理论上可以增加功能，对设置了行间距和段间距的文字计算进行支持。但是目前来说，这种计算方案主要用于资讯Feed流页面中对于多行普通文字的Label高度的计算。

**Comment by dourgulf** [comment]
不只是这些设置会有问题，还要考虑行未逗号，布局会做行距压缩处理的情况。
